server:
  port: 8080

spring:
  application:
    name: raffle
  profiles:
    active: dev
  main:
    allow-circular-references: false
  datasource:
    driver-class-name: ${raffle.datasource.driver-class-name}
    url: jdbc:mysql://${raffle.datasource.host}:${raffle.datasource.port}/${raffle.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${raffle.datasource.username}
    password: ${raffle.datasource.password}
  data:
    redis:
      host: ${raffle.data.redis.host}
      port: ${raffle.data.redis.port}
      password: ${raffle.data.redis.password}
      lettuce:
        pool:
          max-active: ${raffle.data.redis.lettuce.pool.max-active}
          max-idle: ${raffle.data.redis.lettuce.pool.max-idle}
          min-idle: ${raffle.data.redis.lettuce.pool.min-idle}
          time-between-eviction-runs: ${raffle.data.redis.lettuce.pool.time-between-eviction-runs}
# 设置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: a311.college.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 设置pageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true

raffle:
  wechat:
    appid: ${raffle.wechat.appid}
    secret: ${raffle.wechat.secret}
    mchid: ${raffle.wechat.mchid}
    mchSerialNo: ${raffle.wechat.mchSerialNo}
    privateKeyFilePath: ${raffle.wechat.privateKeyFilePath}
    apiV3Key: ${raffle.wechat.apiV3Key}
    weChatPayCertFilePath: ${raffle.wechat.weChatPayCertFilePath}
    notifyUrl: ${raffle.wechat.notifyUrl}
    refundNotifyUrl: ${raffle.wechat.refundNotifyUrl}